### ISSUE TITLE
DuckDuckGo on IPLeaks.net

### ISSUE THREAD

**Issue by cypherpunk** [duckduckgo/duckduckgo#154]
Hello everyone.  

I've noticed today that when I go to www.ipleaks.com from DuckDuckGo, scroll down the page to the section called "Geek Details" and "Detected Informations" there is a line called "Referer (where you came from):" and the DuckDuckGo web address is there.  

This, despite going into the "Advanced Settings" of DuckDuckGo, then "Privacy" and making sure that "Redirect - Prevent sharing of your search with sites you click on" is clicked "on" (I've also tried it with this setting "off" but the same result).

However if I go to ipleaks.net from StartPage.com, this line ("Referer (where you came from):") does not appear.

Does this mean that StartPage.com is more private than DuckDuckGo or does this information not matter?

Is there any way to stop ipleaks.net knowing (or seeing) all the Geek Information at the bottom?

Many thanks.

**Comment by moollaza** [comment]
Hi @cypherpunk 

When you search through DuckDuckGo and visit other sites we don't entirely remove the referer header, but we do strip away everything, besides the domain DuckDuckGo.com. The tells other websites that you arrived there via DuckDuckGo, but it doesn't give them any information about what you searched.

If you were to visit a website from some other search engines, they might not strip the refer which would "leak" your search term to the 3rd party, which we consider a privacy breach.

In certain browsers, like Firefox, we don't use the DDG redirect anymore because the browser automatically cleans up the referer for us. This is because certain browsers, like Firefox, are also trying to make it easier to protect your privacy.

When I searched from StartPage and visited IPLeak, they still had a referer filled out, that said I came from StartPage, but they too had cleaned up the URL so that it didn't show my query.

Knowing that you visited a site by way of DuckDuckGo doesn't really reveal much other than the fact that you conducted some type of search which led you to the website.

By the way, the referer is only passed along when you visit another site via a secure connection (meaning HTTPS -> HTTPS). If the site you're going to isn't secure (HTTP) then no referer is sent. 

I hope this explains things? Even if StartPage is removing the referer entirely, I wouldn't say it makes them "more private". If you really want to prevent the referer from being passed between all secure websites, you can install browser extensions which will do that.

---

Here's an example of a referer **not** being stripped. When you visit IPLeak via Bing, they pass along the full URL, which does reveal to IPLeak the query you searched:
![ip_dns_detect_-_what_is_your_ip__what_is_your_dns__what_informations_you_send_to_websites_](https://cloud.githubusercontent.com/assets/873785/10493174/c16b3814-727d-11e5-9db7-d852f3e6f66c.png)
