### ISSUE TITLE
Make suggestions for !bangs get taken from the site being banged

### ISSUE THREAD

**Issue by Drugoy** [duckduckgo/duckduckgo#178]
I just learned about <a href="https://duckduckgo.com/bang?q=wiki">bangs</a> and I like the idea, but the suggestions there don't match the banged site's suggestions.
Please, make it hook up the banged site's suggestions.

Maybe, it's worth making this optional (say, use double bangs for direct suggestions)...

**Comment by moollaza** [comment]
> but I the suggestions there don't match the banged site's suggestions.
> Please, make it hook up the banged site's suggestions.

@Drugoy thanks for the feedback! Can you clarify what you mean here? An example or screenshot would help. Are you saying the !bang autocomplete isn't correct?

**Comment by Drugoy** [comment]
@moollaza sure.
ddg: 
<img src="http://i.imgur.com/oMH8wMt.png">
wikipedia:
<img src="http://i.imgur.com/5mT1gpN.png">

**Comment by moollaza** [comment]
@Drugoy thanks for clarifying with the image! I now understand what you mean.

To achieve what you're asking, we'd need to be able to access and use the 3rd party website's autocomplete feed or have knowledge of their data.

Though it's a great idea, I don't believe it's possible for us to do that. We currently use our own autocomplete API which helps suggest queries, but I see that it can be a little misleading. 

I'll bring this to the team's attention though so they're aware of your suggestion.

**Comment by Drugoy** [comment]
@moollaza thank you.
But why do you say it's impossible? Do you think those sites will blacklist your server for making too many queries per second?

**Comment by nilnilnil** [comment]
There are a lot of implications:

1) Many sites may consider this abuse.
2) It has the potential to slow down our site / experience.
3) There is potentially an easier method of doing this.

To expound a bit on three, consider how we are using it now:

1) We detect bangs.
2) We use the standard autocomplete once a bang is "completed"

That means that the autocomplete system has no idea about what site it's going to. The quickest, and simplest, way of fixing that is to add the (non abbreviated) bang to the query when a user completes a bang.

1) We detect the bang.
2) We add the bang to the query. !w instead of being ignored is extrapolated as "wikipedia"
3) We continue to add words with that term.

Here is a visual example. We haven't done this yet because it has serious implications, and we're busy working on some other things at the moment.

<img width="993" alt="screen shot 2016-03-08 at 9 52 41 am" src="https://cloud.githubusercontent.com/assets/347240/13605045/a282a352-e513-11e5-923e-33d337b334a3.png">

<img width="999" alt="screen shot 2016-03-08 at 9 52 52 am" src="https://cloud.githubusercontent.com/assets/347240/13605046/a44ad7ea-e513-11e5-90b8-80e3301f369d.png">
