### ISSUE TITLE
New Repository for Roles

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckgo#196]
We have SpiceRoles, GoodieRoles, maybe even FatHeadRoles? All of these are integrated into the ZCI repositories - why? Many of these apply to _several_ if not _all_ of the repositories (already NumberStyle is hardcoded into Goodies _and_ Spice) - we should be able to access them _anywhere_.

I propose a new repository to keep all of our non--repo-specific Roles in; that is to say, things like `NumberStyle`, `Dates`, the upcoming `WhatIs`, and others!

An alternative does present itself, which would be to move the roles into _this_ repository, depending on whether or not we want to keep the role functionality separate. I believe having the roles under the `DDG::Role` or `DDG::Zeroclickinfo::Role` namespace would be appropriate.

I think `duckduckgo/zeroclickinfo-roles` or `duckduckgo/duckduckgo-roles` would be rather catchy names :wink:.

@duckduckgo/community-leaders Any thoughts, objections, _agreement_?

/cc @zachthompson @zekiel @moollaza

**Comment by GuiltyDolphin** [comment]
@mintsoft and I were discussing this last night and he brought up some excellent points about certain impracticalities with this - such as testing and not breaking every IA.

I still think we should be able to access these roles from anywhere though, perhaps we could namespace the roles under `DDG::Role` and have them as an implicit component of the DuckDuckGo repo? Whichever way, it would be handy for all Instant Answers to have access to these roles.

**Comment by moollaza** [comment]
I could see some benefit in putting the roles under the DDG repo, but for the most part Goodies are the IAs using Roles. Fathead and LongTail have never needed any utilities, especially because they're implemented in multiple languages. I think only a handful of Spice use any roles.

Long term, I imagine that handling number and date outputs will be handled on the frontend using localization software, meaning we'd pass a standardized string format and let the frontend determine how it should look (similar to the way we use moment.js)

Handling date/number inputs are likely to be something Spice + Goodies will continue to deal with but arguably it shouldn't be up to the IA dev to deal with them. I could imagine the handler normalizing date/number inputs so that the code can be written assuming the input is of a certain format. However, I don't think this is a big enough problem to warrant putting any effort into that yet.

@zachthompson any thoughts?

**Comment by GuiltyDolphin** [comment]
@moollaza Hmm... I've done some work on adding locale support to the [Dates Role](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2810) and the [NumberStyle Role](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2833) so I could imagine the handler normalizing dates/numbers (probably to ISO8601 or similar) with a standard regex for retrieving them; but we'd probably want people to be able to say if they actually want it normalized?

Anyway, yes - a lot of Roles do deal with standardized parsing and formatting, so perhaps pulling it out of the hands of the user would be best? I.e, they don't have to do any of the work of importing the Role and specifying what to parse?

@mintsoft you've worked on the Roles quite a bit - any ideas?

**Comment by mintsoft** [comment]
Hmm either works; I do like how easy it is to work with roles currently, especially in the Goodies repo (where they're needed most). I think it'd be much harder to work in-and-around them if they were separated out, also more difficult to orchestrate a refactor pulling code from an IA into a role.

**Comment by GuiltyDolphin** [comment]
@mintsoft I agree there is more need for the Roles in Goodies (we have no API that will try and normalize the input); but it'd still be nice to be able to access the GoodieRoles from Spice - can we give Spice access to the `DDG::GoodieRole` namespace @moollaza ?

**Comment by moollaza** [comment]
I spoke to @zachthompson about this and we agreed that we can bring the code from the roles here into the DDG repo.

We can turn it into a lib, and remove the `Moo::Role` requirement as it would make the code more easy to use in places we don't have Moo 👍

**Comment by naqe** [comment]
i propose... felts and welps
