### ISSUE TITLE
Entered keyword not appearing in results

### ISSUE THREAD

**Issue by thany** [duckduckgo/duckduckgo#262]
When I search for `es6 capitalize`, many of the resulting pages do not include the word 'capitalize' (or 'capitalise'). This is true even if I search for `es6 +capitalize`, `es6 "capitalize"` or `es6 +"capitalize"`.

I don't know what else to do frankly. When I enter a keyword, I want the search engine to search for that keyword. Isn't that why I'm entering a keyword in the first place?! Just don't ignore what users are typing in.

**Comment by moollaza** [comment]
This appears to be fixed: https://duckduckgo.com/?q=es6+%2Bcapitalize&ia=web

Regardless, this is unfortunately the wrong place to report search issues. Please use the **Feedback** button located in the bottom-right corner of the search results page.

**Comment by thany** [comment]
Unfortunately, the Feedback option doesn't provide any way for DDG to respond. So I have no way of knowing for sure, if my feedback ends up at a person to look at it, or if it ends up in a black hole.

I suspect someone will actually look at it, but regardless, they have no way to respond to me with maybe some followup questions if neccesary.

**Comment by moollaza** [comment]
@thany I understand, but posting it in the wrong place means its very likely to be seen by the wrong people, or potentially no one. DuckDuckHack is in maintenance mode so these repos are not getting nearly as much attention these days.

If you use the Feedback button it will definitely end up in front of the right person though. We obviously can't follow up with individual users, but chances are if the bug is real and big enough, we'll get a strong signal from several people providing similar feedback, and we'll be able to put the pieces together to figure out what's wrong and what needs to be changed.

**Comment by thany** [comment]
> we'll get a strong signal from several people providing similar feedback

Most people will just move on and use Google, I recon. This kind of prerequisite for a viable issue is not good. An issue is an issue if it exists, not if at least X people report it.

**Comment by 001101** [comment]
@thany Thanks for trashing up Github, good job!!
