### ISSUE TITLE
Feature request: More information for stock/share symbol

### ISSUE THREAD

**Issue by ruchern** [duckduckgo/duckduckgo#266]
### Description
This is a suggestion rather than a bug reporting.

For stocks ticker, is it possible to use a different API to display more information than just the current price?

## Steps to recreate
Just search for example `AAPL` on DuckDuckGo and it returns only the current price from Xignite.

**Comment by moollaza** [comment]
Thanks for the feedback @ruchern.

> is it possible to use a different API to display more information than just the current price?

Xignite probably has additional information, but it may require the use of additional APIs. We only show the price because that's what most people are looking for, and we have the 'More at' link to send users somewhere they can get further info.

Currently, DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.

(this is also the wrong repo. This technically belongs in the Spice Repo, where the code for the Stocks Instant Answer lives: https://github.com/duckduckgo/zeroclickinfo-spice)
