### ISSUE TITLE
Some search results broken

### ISSUE THREAD

**Issue by Wyxuan1** [duckduckgo/duckduckgo#272]
### Description

Hi, I am a longtime user of duckduckgo, but recently saw that while searching for some terms in chrome, the results were coming as 'no result', when there was clearly a help card right next to what should have been the search results. This affects certain searches, but not others. There has been no clear pattern, but this is not an isolated incident. Changing the UA to firefox seems to fix it though.

## Steps to recreate

I have this user agent:
rawUa: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
I wasn't able to reproduce this issue on firefox, as it only seems to affect chrome. I was able to verify that the none of the extensions had caused this error, as I tried the same in incognito mode.
https://duckduckgo.com/?q=compass&atb=v154-4bl&ia=web
https://duckduckgo.com/?q=golang&atb=v154-4bl&ia=web
<img width="1214" alt="Screen Shot 2019-05-28 at 9 52 56 PM" src="https://user-images.githubusercontent.com/24722014/58530404-7be08c80-8193-11e9-9fd4-c1abbb8e552b.png">

**Comment by tcreek** [comment]
This is for the open source project, not the web search

**Comment by moollaza** [comment]
@Wyxuan1 I'm unable to recreate this issue. Do you happen to have any ad blockers enabled for incognito mode in Chrome? I suspect that the call for the link results may have been blocked which is why you're seeing no results. We haven't noticed any other issues, but we'll keep an eye out.

As @tcreek mentioned though, this isn't the correct place to report search result issues. Please use the "Feedback" button at the bottom right corner of the results page to report issues. The right people review those daily and will triage and fix any issues reported.
