### ISSUE TITLE
Issue with !bang 

### ISSUE THREAD

**Issue by sid140** [duckduckgo/duckduckgo#279]
I was just checking !bang feature and I noticed that if there's a space between the ! and the start of the sentence then it's going to the search page rather going to the specified page which has the relevant information. Hopefully, it'll be fixed.

**Comment by moollaza** [comment]
Hey @sid140, when an exclamation is the first or last character in a query, and it's separated by a space, DDG automatically takes you to the first result. I believe that's what you're describing and is expected behaviour.

if the `!` is beside letters associated with a !bang, e.g. `!amazon` then it should be taking you to the website for the bang and performing a search.

I'm going  to close this out, but if you're experiencing something else please let us know and we'll look into it!
