### ISSUE TITLE
clicking on links causes redirections even for POST requests

### ISSUE THREAD

**Issue by vn971** [duckduckgo/duckduckgo#80]
Then problem is with redirections for POST request (they slow-down browsing and don't realy help privacy). See the 3rd comment in this issue, it's more descriptive.

P.S. And big thanks for a cool search engine!

**Comment by moollaza** [comment]
By default, on browsers that support it, we no longer redirect the user, because the browser will strip the referer header when going from HTTPS->HTTP.

If redirects are explicitly enabled, or the browser doesn't super referer stripping, we will redirect through duckduckgo to strip the referer header.

**Comment by vn971** [comment]
@moollaza there does not seem to be any commit referenced. Was the commit made in the proprietary (private) part of DDG ?

**Comment by moollaza** [comment]
Yes, that part is closed source
